version: '3.9'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - pocketbase
  pocketbase:
    image: pocketbase/pocketbase:latest
    command: ["serve", "--http=0.0.0.0:8090"]
    volumes:
      - pb_data:/pb_data
    ports:
      - "8090:8090"

volumes:
  pb_data:
